"""initial migration

Revision ID: 42b3114c6df7
Revises: None
Create Date: 2015-07-05 16:09:48.220504

"""

# revision identifiers, used by Alembic.
revision = '42b3114c6df7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
